import { Ilmoitus } from './Ilmoitus';

export const testiIlmoitukset: Ilmoitus[]=[
    {id: 1,
        henkiloId: 1,
        kuva: "/assets/mustikat.JPG",
        otsikko: "Myydään mustikkaa",
        teksti: "Savonrannalta tänään kerättyä, pudistamatonta mustikkaa 10kg. Nouto kirkonkylältä. Hinta 60e.",
        alue: "Etelä-Savo",
        osasto: "marja",                //marja, sieni, kala, riista
        laji: "Mustikka",
        toiminto: "myydään",            //ostetaan, myydään, annetaan, otetaan
        paivays: "12.8.2019 14:50"},
    {id: 2,
        henkiloId: 2,
        kuva: "",
        otsikko: "Ostaisin kanttarelleja",
        teksti: "Enintään 10l. Pienetkin määrät kelpaavat. Savonlinnan lähiseutu. Voin hakea.",
        alue: "Etelä-Savo",
        osasto: "sieni",         
        laji: "Kanttarelli",
        toiminto: "ostetaan",
        paivays: "12.8.2019 14:50"},
    {id: 3,
        henkiloId: 3,
        kuva: "/assets/sorsat.jpg",
        otsikko: "Sorsia myynnissä",
        teksti: "Heippa, jos olet kiinnostunut kokonaisista sorsista 15e/kpl niin ota yhteyttä. Sovitaan metsästyspäivistä.",
        alue: "Pohjois-Karjala",
        osasto: "riista",         
        laji: "Vesilinnut",
        toiminto: "myydään",
        paivays: "12.8.2019 14:50"},
    {id: 4,
        henkiloId: 2,
        kuva: "",
        otsikko: "Myyn sekasieniä",
        teksti: "Enintään 10l.",
        alue: "Kainuu",
        osasto: "sieni",         
        laji: "kaikki",
        toiminto: "myydään",
        paivays: "12.8.2019 14:50"},
    {id: 5,
        henkiloId: 3,
        kuva: "",
        otsikko: "Ostaisin ahvenia",
        teksti: "Pienetkin määrät kelpaavat. Savonlinnan lähiseutu. Voin hakea.",
        alue: "Etelä-Savo",
        osasto: "kala",         
        laji: "Ahven",
        toiminto: "ostetaan",
        paivays: "12.8.2019 14:55"},
    {id: 6,
        henkiloId: 1,
        kuva: "/assets/puolukat.jpg",
        otsikko: "Myydään puolukkaa",
        teksti: "Kerään puolukkaa pyynnöstä. Hinta 55e/10kg.",
        alue: "Pohjois-Savo",
        osasto: "marja",         
        laji: "Puolukka",
        toiminto: "myydään",
        paivays: "12.8.2019 14:50"},
    {id: 7,
        henkiloId: 2,
        kuva: "",
        otsikko: "Ylimääräistä pikkukalaa",
        teksti: "Olen lähes joka viikonloppu pilkillä ja yleensä pikkukalaa, enimmäkseen ahventa, saa heittää lokeille. Laita viestiä jos kiinnostaa!",
        alue: "Kymenlaakso",
        osasto: "kala",        
        laji: "Ahven",
        toiminto: "annetaan",
        paivays: "11.11.2019 14:50"},
    {id: 8,
        henkiloId: 3,
        kuva: "",
        otsikko: "Hirven lihaa myynnissä",
        teksti: "Hyvinkään metsästyseura myy huutokaupassa 20.10.2019 klo15 metsästysmajalla (Riistapolku 3) tuoretta hirven lihaa. Tervetuloa!",
        alue: "Päijät-Häme",
        osasto: "riista",         
        laji: "Hirvi",
        toiminto: "myydään",
        paivays: "12.8.2019 14:50"},
    {id: 9,
        henkiloId: 2,
        kuva: "",
        otsikko: "Mummille pikkukaloja",
        teksti: "Mummini luvalla ilmoitan, että hänelle voi viedä ylimääräisiä kaloja. Kiitos!",
        alue: "Kainuu",
        osasto: "kala",         
        laji: "kaikki",
        toiminto: "otetaan",
        paivays: "12.8.2019 14:50"},
    {id: 10,
        henkiloId: 3,
        kuva: "",
        otsikko: "Ostaisin peuran lihaa",
        teksti: "Tarjoa rohkeasti, voin hakea etempääkin!",
        alue: "Uusimaa",
        osasto: "riista",         
        laji: "Peura",
        toiminto: "ostetaan",
        paivays: "12.8.2019 14:55"}
    ]